### ISSUE TITLE
bk details <log-id> is giving status: Unknown for ledger_details

### ISSUE THREAD

**Issue by Richa-Srivastava** [pravega/pravega-tools#34]
Output of `bk details <log-id>` is giving `"status": "Unknown"` for `"key": "ledger_details"` section:
```
bk details 0
{
  "key": "log_summary",
  "value": {
    "logId": 0,
    "epoch": 4,
    "version": 311,
    "enabled": true,
    "ledgers": 1,
    "truncation": "Sequence = 17179886001, LedgerId = 3903, EntryId = 16817"
  }
}
{
  "key": "ledger_details",
  "value": {
    "ledger": 3903,
    "seq": 4,
    "status": "Unknown",
    "lac": 16994,
    "length": 173382663,
    "numBookies": 3,
    "numFragments": 1,
    "ensembleSize": 3,
    "writeQuorumSize": 3,
    "ackQuorumSize": 2,
    "ensembles": "0: [pravega-bookie-0.pravega-bookie-headless.default.svc.cluster.local:3181,pravega-bookie-1.pravega-bookie-headless.default.svc.cluster.local:3181,pravega-bookie-2.pravega-bookie-headless.default.svc.cluster.local:3181]"
  }
}
```
Following is my `config.properties` file's detail:
```
#
# Copyright (c) 2017 Dell Inc., or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#

# Config for CLI credentials (at the moment, Controller auth is only supported).
cli.authEnabled=false
cli.userName=admin
cli.password=1111_aaaa

# Config for CLI Controller REST/GRPC endpoints.
cli.controllerRestUri=http://172.24.83.11:10080
cli.controllerGrpcUri=tcp://172.24.83.11:9090
cli.metadataBackend=segmentstore

# General configuration for the Pravega cluster at hand.
pravegaservice.clusterName=pravega
pravegaservice.containerCount=32

# Config for Zookeeper service.
pravegaservice.zkURL=172.24.83.3:2181

# Config for Bookkeeper commands.
bookkeeper.bkLedgerPath=/pravega/pravega/bookkeeper/ledgers
```

**Comment by Richa-Srivastava** [comment]
@RaulGracia this issue is seen in `0.6.0-2408.7312399` cli also. Please take a look.

**Comment by andreipaduroiu** [comment]
All `LedgerMetadata` is created with a status of `Unknown` (which is fine, it doesn't mean something bad).

As ledgers are rolled over or recovered, the code in the [here](https://github.com/pravega/pravega/blob/c4e6dd85c1d8c662cbae953f68533c485d13fafc/segmentstore/storage/impl/src/main/java/io/pravega/segmentstore/storage/impl/bookkeeper/LogMetadata.java#L200) updates them to either `Empty` or `NotEmpty`. It is only important if it's `Empty` as those ledgers are immediately deleted since they provide no value.

If you trace the usages of `Unknown` in the code, you'll see that it gets special treatment and get updated after they are open-fenced (in `Ledgers.openFence`). Following though the code leads you back the link I shared above.

Eventually all ledgers will end up as `Empty` or `NotEmpty`, but newly created (and not-yet-fenced) ledgers will not have it set until they are properly checked.

Nothing to worry about here.
